CREATE TABLE bloqueo_mantenimiento (id SERIAL NOT NULL, fecha_inicio timestamp NOT NULL, fecha_fin timestamp, motivo varchar(255), canchaid int4 NOT NULL, PRIMARY KEY (id));
CREATE TABLE cancha (id SERIAL NOT NULL, nombre varchar(255) NOT NULL, costo_base_hora numeric(19, 0) NOT NULL, activa int2 NOT NULL, sedeid int4 NOT NULL, tipo_canchaid int4 NOT NULL, PRIMARY KEY (id));
CREATE TABLE clase_grupal (id SERIAL NOT NULL, horario timestamp NOT NULL, tipo_claseid int4 NOT NULL, instructorid int4 NOT NULL, capacidad_maxima int4 NOT NULL, sedeid int4 NOT NULL, fecha date NOT NULL, PRIMARY KEY (id));
CREATE TABLE codigo_qr (id SERIAL NOT NULL, token varchar(255) NOT NULL, expira_en timestamp NOT NULL, usuarioid int4 NOT NULL, PRIMARY KEY (id));
CREATE TABLE comprobante (id SERIAL NOT NULL, numero_comprobante varchar(255) NOT NULL, url_pdf varchar(255), fecha_emision timestamp NOT NULL, pagoid int4 NOT NULL, PRIMARY KEY (id));
CREATE TABLE detalle_facturacion (id SERIAL NOT NULL, concepto varchar(255) NOT NULL, cantidad int4 NOT NULL, subtotal numeric(19, 0) NOT NULL, comprobanteid int4 NOT NULL, PRIMARY KEY (id));
CREATE TABLE inscripcion_espera (id SERIAL NOT NULL, posicion int4 NOT NULL, notificado int2 NOT NULL, usuarioid int4 NOT NULL, clase_grupalid int4 NOT NULL, PRIMARY KEY (id));
CREATE TABLE instructor (id SERIAL NOT NULL, nombre varchar(255) NOT NULL, apellido varchar(255) NOT NULL, PRIMARY KEY (id));
CREATE TABLE membresia (id SERIAL NOT NULL, fecha_inicio timestamp NOT NULL, estado varchar(255) NOT NULL, fecha_fin timestamp NOT NULL, renovacion_automatica int2 NOT NULL, usuarioid int4 NOT NULL, plan_membresiaid int4 NOT NULL, sedeid int4 NOT NULL, PRIMARY KEY (id));
CREATE TABLE pago (id SERIAL NOT NULL, monto numeric(19, 0) NOT NULL, tipo_referencia varchar(255) NOT NULL, referencia_id int4 NOT NULL, fecha_pago timestamp NOT NULL, usuarioid int4 NOT NULL, estado varchar(255) NOT NULL, PRIMARY KEY (id));
CREATE TABLE penalizacion_clase (fecha_inicio date NOT NULL, fecha_fin date NOT NULL, motivo varchar(255), usuarioid int4 NOT NULL, id SERIAL NOT NULL, PRIMARY KEY (id));
CREATE TABLE plan_membresia (id SERIAL NOT NULL, nombre varchar(255) NOT NULL UNIQUE, duracion_meses int4 NOT NULL, precio numeric(19, 0) NOT NULL, PRIMARY KEY (id));
CREATE TABLE referencia_pasarela (id SERIAL NOT NULL, token varchar(255) NOT NULL, proveedor varchar(255) NOT NULL, pagoid int4 NOT NULL, PRIMARY KEY (id));
CREATE TABLE registro_acceso (id SERIAL NOT NULL, fecha_hora_ingreso timestamp NOT NULL, fecha_hora_salida timestamp, usuarioid int4 NOT NULL, sedeid int4 NOT NULL, PRIMARY KEY (id));
CREATE TABLE reserva_cancha (id SERIAL NOT NULL, precio_aplicado numeric(19, 0) NOT NULL, estado varchar(255) NOT NULL, turno_canchaid int4 NOT NULL, usuarioid int4 NOT NULL, PRIMARY KEY (id));
CREATE TABLE reserva_clase (id SERIAL NOT NULL, fecha_reserva timestamp NOT NULL, estado_asistencia varchar(255) NOT NULL, clase_grupalid int4 NOT NULL, usuarioid int4 NOT NULL, estado_reserva varchar(255) NOT NULL, PRIMARY KEY (id));
CREATE TABLE rol (id SERIAL NOT NULL, nombre varchar(50) NOT NULL UNIQUE, PRIMARY KEY (id));
CREATE TABLE sede (id SERIAL NOT NULL, nombre varchar(255) NOT NULL, direccion varchar(255), capacidad_maxima int4 NOT NULL, PRIMARY KEY (id));
CREATE TABLE tipo_cancha (id SERIAL NOT NULL, nombre varchar(255) NOT NULL, PRIMARY KEY (id));
CREATE TABLE tipo_clase (id SERIAL NOT NULL, nombre varchar(255) NOT NULL, PRIMARY KEY (id));
CREATE TABLE turno_cancha (id SERIAL NOT NULL, fecha date NOT NULL, hora_inicio time(7) NOT NULL, hora_fin time(7) NOT NULL, canchaid int4 NOT NULL, PRIMARY KEY (id));
CREATE TABLE usuario (id SERIAL NOT NULL, dni varchar(255) NOT NULL UNIQUE, email varchar(255) NOT NULL UNIQUE, rolid int4 NOT NULL, sedeid int4 NOT NULL, nombre varchar(255) NOT NULL, apellido varchar(255) NOT NULL, foto varchar(255), contrasenia varchar(255) NOT NULL, PRIMARY KEY (id));
CREATE UNIQUE INDEX turno_cancha ON turno_cancha (canchaid, fecha, hora_inicio);
ALTER TABLE usuario ADD CONSTRAINT FKusuario32982 FOREIGN KEY (rolid) REFERENCES rol (id);
ALTER TABLE membresia ADD CONSTRAINT FKmembresia738723 FOREIGN KEY (usuarioid) REFERENCES usuario (id);
ALTER TABLE membresia ADD CONSTRAINT FKmembresia60619 FOREIGN KEY (plan_membresiaid) REFERENCES plan_membresia (id);
ALTER TABLE membresia ADD CONSTRAINT FKmembresia128458 FOREIGN KEY (sedeid) REFERENCES sede (id);
ALTER TABLE usuario ADD CONSTRAINT FKusuario576001 FOREIGN KEY (sedeid) REFERENCES sede (id);
ALTER TABLE registro_acceso ADD CONSTRAINT FKregistro_a164040 FOREIGN KEY (usuarioid) REFERENCES usuario (id);
ALTER TABLE registro_acceso ADD CONSTRAINT FKregistro_a940368 FOREIGN KEY (sedeid) REFERENCES sede (id);
ALTER TABLE codigo_qr ADD CONSTRAINT FKcodigo_qr98568 FOREIGN KEY (usuarioid) REFERENCES usuario (id);
ALTER TABLE clase_grupal ADD CONSTRAINT FKclase_grup750856 FOREIGN KEY (tipo_claseid) REFERENCES tipo_clase (id);
ALTER TABLE clase_grupal ADD CONSTRAINT FKclase_grup575819 FOREIGN KEY (instructorid) REFERENCES instructor (id);
ALTER TABLE reserva_clase ADD CONSTRAINT FKreserva_cl951980 FOREIGN KEY (clase_grupalid) REFERENCES clase_grupal (id);
ALTER TABLE reserva_clase ADD CONSTRAINT FKreserva_cl485327 FOREIGN KEY (usuarioid) REFERENCES usuario (id);
ALTER TABLE inscripcion_espera ADD CONSTRAINT FKinscripcio475075 FOREIGN KEY (usuarioid) REFERENCES usuario (id);
ALTER TABLE clase_grupal ADD CONSTRAINT FKclase_grup901111 FOREIGN KEY (sedeid) REFERENCES sede (id);
ALTER TABLE reserva_cancha ADD CONSTRAINT FKreserva_ca451621 FOREIGN KEY (turno_canchaid) REFERENCES turno_cancha (id);
ALTER TABLE reserva_cancha ADD CONSTRAINT FKreserva_ca826686 FOREIGN KEY (usuarioid) REFERENCES usuario (id);
ALTER TABLE pago ADD CONSTRAINT FKpago806410 FOREIGN KEY (usuarioid) REFERENCES usuario (id);
ALTER TABLE referencia_pasarela ADD CONSTRAINT FKreferencia44391 FOREIGN KEY (pagoid) REFERENCES pago (id);
ALTER TABLE comprobante ADD CONSTRAINT FKcomprobant739681 FOREIGN KEY (pagoid) REFERENCES pago (id);
ALTER TABLE detalle_facturacion ADD CONSTRAINT FKdetalle_fa331535 FOREIGN KEY (comprobanteid) REFERENCES comprobante (id);
ALTER TABLE inscripcion_espera ADD CONSTRAINT FKinscripcio962232 FOREIGN KEY (clase_grupalid) REFERENCES clase_grupal (id);
ALTER TABLE turno_cancha ADD CONSTRAINT FKturno_canc933562 FOREIGN KEY (canchaid) REFERENCES cancha (id);
ALTER TABLE bloqueo_mantenimiento ADD CONSTRAINT FKbloqueo_ma58773 FOREIGN KEY (canchaid) REFERENCES cancha (id);
ALTER TABLE cancha ADD CONSTRAINT FKcancha514768 FOREIGN KEY (sedeid) REFERENCES sede (id);
ALTER TABLE cancha ADD CONSTRAINT FKcancha57615 FOREIGN KEY (tipo_canchaid) REFERENCES tipo_cancha (id);
