-- Schema de FitZone Sports (modulo auth), extraido del esquema real generado por Hibernate.
-- Uso: correr manualmente contra una base nueva (ej. Neon) antes de apuntar el perfil "prod"
-- (que usa ddl-auto=validate y no crea tablas por si solo).

CREATE TABLE roles (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    CONSTRAINT uk_roles_nombre UNIQUE (nombre)
);

CREATE TABLE usuarios (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre   VARCHAR(255),
    apellido VARCHAR(255),
    dni      VARCHAR(255),
    email    VARCHAR(255),
    password VARCHAR(255),
    activo   BOOLEAN NOT NULL DEFAULT TRUE,
    rol_id   BIGINT NOT NULL,
    CONSTRAINT uk_usuarios_email UNIQUE (email),
    CONSTRAINT uk_usuarios_dni UNIQUE (dni),
    CONSTRAINT fk_usuarios_rol FOREIGN KEY (rol_id) REFERENCES roles(id)
);
